apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    ctfd: ctf-pv
    app: ctf-logs
  name: ctf-logs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    ctfd: ctf-pv
    app: ctf-uploads
  name: ctf-uploads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.app_name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      volumes:
      - name: ctf-logs
        persistentVolumeClaim:
          claimName: ctf-logs
      - name: ctf-uploads
        persistentVolumeClaim:
          claimName: ctf-uploads
      containers:
      - name: {{ .Values.app_name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        env:
          - name: UPLOAD_FOLDER
            value: {{ .Values.containers.env.UPLOAD_FOLDER }}
          - name: DATABASE_URL
            value: {{ .Values.subprotocol.db }}{{ .Values.login }}{{ .Values.password }}{{ .Values.dbPodName }}{{ .Values.namespace }}{{ .Values.clusterName }}{{ .Values.dbname }}
          - name: REDIS_URL
            value: {{ .Values.subprotocol.redis }}{{ .Values.password }}{{ .Values.redisPodName }}{{ .Values.namespace }}{{ .Values.clusterName }}{{ .Values.redisPort }}{{ .Values.dbname }}
          - name: WORKERS
            value: !!toString {{.Values.containers.env.WORKERS }}
          - name: LOG_FOLDER
            value: {{ .Values.containers.env.LOG_FOLDER }}
          - name: ACCESS_LOG
            value: "-"
          - name: ERROR_LOG
            value: "-"
          - name: REVERSE_PROXY 
            value: "true"
        volumeMounts:
        - mountPath: /var/log/CTFd
          name: ctf-logs
        - mountPath: /var/uploads
          name: ctf-uploads
