apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{ .Values.app_name }}
  ports:
    - protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.containerPort }}